#ifndef GUARD_WINRSRC_H
#define GUARD_WINRSRC_H

#define ID_APPICON 2

#define ID_DIALOG_KEYS  100
#define ID_EDIT_ABUTTON 101
#define ID_EDIT_BBUTTON 102
#define ID_EDIT_STARTBUTTON 103
#define ID_EDIT_SELECTBUTTON 104
#define ID_EDIT_DPADUP 105
#define ID_EDIT_DPADDOWN 106
#define ID_EDIT_DPADLEFT 107
#define ID_EDIT_DPADRIGHT 108
#define ID_EDIT_FFWDBUTTON 109

#define ID_DIALOG_HELP 200

#define ID_DIALOG_ABOUT 300

#define ID_BTN_APPLY 400


#endif  // GUARD_WINRSRC_H
